### ISSUE TITLE
i can not use xidle with file

### ISSUE THREAD

**Issue by esmmusavi** [Freezystem/xidel#2]
Hi.
I can not use xidle with file
`docker run --rm -it freezystem/xidel file.html -e "//title"`

**Comment by Freezystem** [comment]
Indeed, I just tried it myself and got:

```
**** Retrieving: file.html ****
An unhandled exception occurred at $000000000047DF55:
EFOpenError: Unable to open file "file.html"
  $000000000047DF55
  $000000000047DD54
  $000000000045E9E2
 ```
 
I'll investigate shortly

**Comment by Freezystem** [comment]
Don't know yes if it's related but reading from `stdin` does not work either:
`cat file.html | docker run --rm -it freezystem/xidel:alpine - -e "//title"`

> the input device is not a TTY

Tried both commands within the docker container and it works so it must be a docker related issue. 
I'll investigate in this way first.

**Comment by Freezystem** [comment]
Ok, so the syntax was wrong. 
To read from a file from within a docker container you have to mount the folder containing the file in the container.

You can workaround this problem by mounting the current folder as a volume like this:
`docker run --rm -it -v `pwd`:/tmp freezystem/xidel /tmp/file.html -e "//title"`

Here we mount our current working directory to the `/tmp` folder.
Be careful to specify the correct path that leads to the file within the docker container (here it's `/tmp/file.html`).

You can also use the `stdin` syntax if you prefer:
`cat file.html | docker run --rm -i freezystem/xidel - -e "//title"`

You just have to omit the `-t` (`--tty`) option to make it work.

**Comment by Freezystem** [comment]
@esmmusavi feel free to reopen this issue or ask if you have any question.
Hope it solves your problem.
